### ISSUE TITLE
Join Event by Location Screen - programming

### ISSUE THREAD

**Issue by almonzer** [certainlyakey/advanced-jukebox-ios#5]
I as a user would like to Be able to join a playlist by reading a QR code

**Comment by certainlyakey** [comment]
We need this screen to be built according to the high fidelity prototype made by Ottavio ([ios-resources/Design mockup](https://github.com/certainlyakey/advanced-jukebox-ios/tree/master/ios-resources/Design%20mockup) folder). 
Only the simplest functions here - clicking any item in the list of venues (upper part) or typing any characters in the barcode field makes the app to go to the playlist screen.
