### ISSUE TITLE
Playlist screen - programming

### ISSUE THREAD

**Issue by almonzer** [certainlyakey/advanced-jukebox-ios#6]
I as a user would like to :
Be able to see a song's name
Be able to see a song's album
Be able to see a song's artist 
Be able to see a song's album art
Be able to use the Heart button for when I like a song
Be able to unheart a song he hearted it before
Be able to use the Super heart button when long pressed on the heart button
be able to search the content of the playlist 
Be able to vote by swiping right for yes and left for no
Be able to swipe up to see screen only for one song

I as a registered user would like to:
Be able to bring his/her profile photo from Facebook to the app
Be able to see my profile picture

**Comment by certainlyakey** [comment]
Now that data in the playlist view is live (loaded from database), we need here:
1. name of the playlist (without any functionality, simply decorative, no need to load it from database. May be called for instance "Jazz event")
2. current number of songs (count from number of songs currently displayed)
3. name of artist, number of votes, vote button for each song
4. search icon which will transition to the search screen
5. back button which will transition to the select (join) playlist screen.

**Comment by certainlyakey** [comment]
The prototype screen is [here](https://drive.google.com/file/d/0B8gXjcxUp9DsaUl4ckRFRlpNT2c/view).
